-- Twen Chat Plugin - AI Chat Interface for Twen Vim
-- :Chat   - Open chat window
-- :ChatSet - Configure AI provider
--
-- The chat module is loaded directly in init.lua (not via lazy.nvim plugin spec)
-- to avoid lazy.nvim trying to clone a non-existent remote repository.
-- This file is kept for documentation purposes only.
--
-- Keymaps:
--   <leader>ci  Open Twen Chat
--   <leader>cs  Open Chat Settings
--
-- Commands:
--   :Chat       Open chat window
--   :ChatSet    Configure AI provider
