-- Twen Chat Plugin - AI Chat Interface for Twen Vim
-- This file documents the chat features.
-- The actual implementation lives in lua/twen/chat/init.lua
-- and is loaded automatically by init.lua on startup.
--
-- Commands:
--   :Chat       Open AI chat window (top: history, bottom: input)
--   :ChatSet    Configure AI provider settings
--
-- Keymaps (after setup):
--   <leader>ci  Open Twen Chat
--   <leader>cs  Open Chat Settings
--
-- Chat window controls:
--   Enter       Send message
--   Ctrl+J      Insert new line (multiline input)
--   Esc         Close chat
--
-- Settings controls:
--   j/k         Navigate providers
--   x/Enter     Select provider
--   Ctrl+s      Save and close
--   Esc/q       Close without saving
--
-- Supported providers:
--   NVIDIA NIM, Claude, ChatGPT, Gemini, Groq, Mistral,
--   DeepSeek, Ollama, Together AI, Perplexity AI
